name: "BlockProtect"
version: "1.0"
main: "me.martinitslinda.blockprotect.BlockProtect"
author: "MartinItsLinda"
softdepend: [WorldGuard]
description: ""

commands:
    blockprotect:
        usage: "/blockprotect <blockId> <blockData>"